version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./backend:/usr/app
    environment:
      SKIP_PREFLIGHT_CHECK: process.env.SKIP_PREFLIGHT_CHECK
      MONGODB_URL: process.env.MONGODB_URL
      DBUSERNAME: process.env.DBUSERNAME
      DB_PASSWORD: process.env.DB_PASSWORD
      DB_NAME: process.env.DB_NAME
      JWT_SECRET: process.env.JWT_SECRET
      PAYPAL_CLIENT_ID: process.env.PAYPAL_CLIENT_ID
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/app/node_modules
      - ./frontend:/usr/app
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - 80:80
